### PR TITLE
feat: add CodeDeploy deployment config name parameter

### PR DESCRIPTION
**Pull request by project0**
*Issue #, if available:*

*Description of changes:*
Allows to overwrite the desired deployment configuration for CodeDeploy

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by snoworc** [comment]
Duplicate of #506 ?

**Comment by amazreech** [comment]
Hi @project0, 

Thank you for your Patience. We appreciate your contribution to the repository and will be working to review the changes in the Pull Request. 
In the meantime please ensure that below steps, if not already completed, are taken care of in your Pull Request:

1. Verify if PR follows semantic pull request [conventions](https://www.conventionalcommits.org/en/v1.0.0/#specification).

2. Please run `npm run package` command to update dist/ folder with latest dependencies.

3. Resolve merge conflicts on the PR

**Comment by project0** [comment]
> Please run npm run package command to update dist/ folder with latest dependencies.

@amazreech looks like the CI does not like that

**Comment by amazreech** [comment]
> > Please run npm run package command to update dist/ folder with latest dependencies.
> 
> @amazreech looks like the CI does not like that

Hi @project0, is there any issue you are facing when trying to `npm run package` to update the `dist` folder?

**Comment by project0** [comment]
@amazreech https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/master/.github/workflows/package.yml#L35-L38
PRs are not supposed to update the dist file.

**Comment by amazreech** [comment]
> @amazreech https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/master/.github/workflows/package.yml#L35-L38 PRs from contributors are not supposed to update the dist file.

@project0 Thank you for your response, as per the current setup, I believe the line of code `git diff --exit-code dist/index.js` returns exit code `0` (Pass) if there are no differences and `non-zero` (Fail) if there are any differences.

For the `git diff --exit-code dist/index.js` to have no differences (exit code 0 | Package Check to pass) the dist file needs to updated to contain latest changes. 

Please let me know if there any additional concerns you might have.

**Pull request merged**
