### PR TITLE
feat: Allow setting codedeploy-config-name as input

### PR DESCRIPTION
**Pull request by c-ameron**
*Issue #479 , if available:*

*Description of changes:*

This allows the setting of the [config name](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html) of the deployment in Code Deploy via the `codedeploy-config-name` input variable.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by snoworc — APPROVED** [review]
👍 

I like it, i like to have fast, normal, slow deployment roll options. depending on environment, time of day, whether manual or automated, etc. This allows us to do this in the ci/cd flow instead of terraforming a change to the deployment object first.

**Review by llxff — APPROVED** [review]

**Comment by c-ameron** [comment]
@iamhopaul123 @KollaAdithya are you able to have a look at this PR? Thanks!

**Review by iamhopaul123 — APPROVED** [review]

**Comment by alekgosk** [comment]
Any updates on merging one? Would love to get away form using a fork as a workaround :)

**Comment by amazreech** [comment]
Hi @c-ameron,

Thank you for your Patience. We appreciate your contribution to the repository and will be working to review the changes in the Pull Request. We will reach-out if with any questions or suggestions during the review.

In the meantime please ensure that below steps, if not already completed, are taken care of in your Pull Request:

1. Verify if PR follows semantic pull request [conventions](https://www.conventionalcommits.org/en/v1.0.0/#specification).

2. Resolve any merge conflicts on the PR

3. Please run `npm run package` command to update dist/ folder with latest dependencies. This will allow the Package status check to pass.

**Comment by amazreech** [comment]
Hi, Thank you for your contribution in this PR.  We have recently merged a PR that covers these changes. [PR #540](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/540). The changes will be released as part of next release.

Closing this PR, please feel free to re-open or create additional PRs for other feature requests or support needed.

Thank you!

**Pull request closed without merging**
