### PR TITLE
chore: Upgrade to Node 20, remove deprecation warnings, upgrade CI deprecations 

### PR DESCRIPTION
**Pull request by singhprd**
Fix for https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/535

The upgrading of the checkout action is a dup of this PR which hasn't had much attention given to it, this is a safe upgrade though so just pulling it in here anyway: https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/471

- Use non-deprecated node runtime
- Brucey bonus: Upgrade to non-deprecated checkout action (v2 -> v4)
- Update yarn lockfile
- Update dist

This is currently affecting my workflows by adding lots of annotations, cluttering up the Actions experience. 😞 
Screenshot 2024-02-07 at 12 44 35

It would be great if the maintainers here could upgrade the Node version to resolve this. This PR is a start on that, I'm not sure if I've missed anything. Tested it on our repo and it seems to work.

Thanks

### CODE REVIEW

**Comment by singhprd** [comment]
@efekarakus / @dannyrandall / AWS maintainers (📯) , it would be great if you had any time to have a look at getting these deprecations looked at, cheers!

**Comment by TheMoonDawg** [comment]
Any updates to this?

**Review by wilkinson4 — APPROVED** [review]

**Comment by almiavicas** [comment]
2 months to go for the Github enforcement of Node 20 usage! https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

I'm not sure how this will impact users, but it would be really nice for the community to have this upgrade done before that date. This is a great Github Action and I would love to keep using it. Let me know if I can help in any way to get this merged!

**Review by KollaAdithya — APPROVED** [review]

**Comment by ZsoltPath** [comment]
@KollaAdithya thanks for approving and merging this! Can we get a release now?

**Comment by cabello** [comment]
Hi there, I see this has been merged but I don't see a release yet, should we just point to master or wait for a release?

**Comment by jedipunkz** [comment]
@KollaAdithya 
Please release tag. GitHub plans to transition to run on Node 20 by Spring 2024.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date.

**Comment by wilkinson4** [comment]
Starting to wonder if this action is still maintained.

**Comment by patrick-scully-ef** [comment]
> Starting to wonder if this action is still maintained.

I pinned the commit SHA instead of the version

**Pull request merged**
